### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#1]
El favicon surt estirat, i el text hauria de ser: Inèdit - Autoavalua't (o en l'idioma que toqui). Si això de canviar l'idioma és molt difícil, posem: Inèdit - Circular

![image](https://user-images.githubusercontent.com/42779858/81542349-cb07d900-9374-11ea-9a03-fe51d90c2e8a.png)

**Comment by codwell** [comment]
fet

**Comment by andriusmp** [comment]
Ok! Només que en anglès seria 'Self-assessment'

**Comment by codwell** [comment]
La traducció de "Autoavalua't" (imperatiu) es "Self-assess".
"Self-assesment" es traduirïa com "Autoavaluació". (Sustantiu)
Estàs segura de que vols tindre eixa diferencia entre idiomes, no pareix massa logic i el problema es que si en algun altre lloc utilitzem la paraula "Self-assessment" a soles sempre es traduirà com "Autoavalua't".

**Comment by andriusmp** [comment]
Ja, som conscients de la diferència. És que en anglès seria més aviat 'Self-assess yourself', i queda una mica malament. Així que ho adaptem i en anglès posem el sustantiu. Gràcies! :)
No sé si he acabat' d'entendre això de la traducció si està la paraula a soles. Vols dir que al fer aquesta relació, és una traducció que s'agafa per la resta de continguts i poden quedar altres textos incorrectes? Si això és problemàtic, canviem el text del favicon, posem a tot arreu Inèdit - Circular y fiesta

**Comment by codwell** [comment]
Si, si en algun lloc hi haguera eixa paraula a soles es traduirïa de la mateixa manera. Ho acabe de buscar a tot el codi i veig que de moment no passa. Ho canviaré ara.

**Comment by codwell** [comment]
Corregit a local.

**Comment by andriusmp** [comment]
Ok!
