### ISSUE TITLE
Pop-ups

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#11]
- Falten títols a alguns pop-ups: el de sectors i el d'instruccions
- A tots: Podem aprofitar la barra superior per posar-hi els títols? Queda molt espai en blanc i després el text molt enganxat al títol. Si no es pot aprofitar la barra superior, pujar el títol i afegir espai abans del text.
![image](https://user-images.githubusercontent.com/42779858/81556539-ccdc9700-938a-11ea-9050-cd2b6b8eba89.png)

- Instruccions: Els subtítols han de seguir la lógica dels altres pop-ups: justificats esquerra/tiempos headline regular/taronja. Per '+instruccions' i '+info', utilitzar la mateixa mida que la resta de text (14px)
![image](https://user-images.githubusercontent.com/42779858/81583482-bc8be280-93b1-11ea-9529-50b1fe7d7f7e.png)

**Comment by codwell** [comment]
Fet a local.

**Comment by andriusmp** [comment]
Ok!
