### ISSUE TITLE
Error subsector

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#12]
Si l'usuari està a la pantalla d'instruccions (just al començar el test) i tira cap enrera, l'aplicació torna a la pantalla inicial, guardant els camps que l'usuari havia introduït, excepte el subsector que, a més, té el desplegable buit.
![image](https://user-images.githubusercontent.com/42779858/81556976-7f145e80-938b-11ea-9249-f3231e80dbeb.png)

Es soluciona quan torna a seleccionar sector.

**Comment by codwell** [comment]
Aquesta ha sigut complicada de resoldre. Al tornar enrere es el navegador el que ompli el formulari amb dades de la cache y no genera el event intern de "s'ha seleccionat un sector".
Resolt a local.

**Comment by andriusmp** [comment]
Ok!
