### ISSUE TITLE
Exportar a PDF

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#15]
- Títol sense majúscules (tipus oració)
- Espaiat entre línies: línies massa juntes
- Baixar l'opacitat de el logo de l'encapçalament de la primera pàgina (logo inèdit i mig cercle)
- Canviar color dels enllaços per a que sigui com la web (taronja)
- Ajustar l'espai de després del gràfic per a que sigui el mateix que el superior
- Afegir també l'intro a 'Fabricació i distribució'

![image](https://user-images.githubusercontent.com/42779858/81558772-9143cc00-938e-11ea-922b-ae15409acb94.png)

**Comment by codwell** [comment]
Fet

**Comment by andriusmp** [comment]
Alguna cosa ha passat, perquè em dona un 'Internal error' al exportar

**Comment by andriusmp** [comment]
Tot ok!!
