### ISSUE TITLE
Pantalla inicial

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#16]
- El text (i el cercle) queden molt amunt, sense espai a dalt i amb molt espai a baix. Caldria centrar-ho verticalment.
- El text de les icones queda desquadrat.
- Falta la línia taronja superior (a totes les pantalles)
- Afegir un espai entre el títol (Bienvenido...) i el text i els inputbox.

![image](https://user-images.githubusercontent.com/42779858/81581374-f27b9780-93ae-11ea-8eee-9da22ce4ec54.png)

**Comment by codwell** [comment]
Corregit.
O això crec, la part del quadret verd no l'acabo d'entendre Quan pugi la nova versió em dius si està tot.

**Comment by andriusmp** [comment]
Ok! (la part del quadret verd està explicada fatal, no m'estranya que no ho entenguis xD)
