### ISSUE TITLE
Pantalla qüestionari

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#17]
- Les mides de les tipos no concorden amb les specs i, en general, es veuen totes força petites:
1. Augmentar el títol (que estava especificat a 40px) fins a 45px (d'aquí endavant)
2. Seguir la resta de mides de les specs (veure imatge més abaix per facilitar)
- El botó '+info' hauria d'estar més enganxat al títol que a les caixes de resposta
![image](https://user-images.githubusercontent.com/42779858/81581949-ba288900-93af-11ea-9a43-175feefdc268.png)
- Les capses de les preguntes no sempre estan distanciades de les fletxes. Posar una amplària màxima més ajustada.
![image](https://user-images.githubusercontent.com/42779858/81582158-fb209d80-93af-11ea-94a0-a735c3b249fc.png)

**Comment by codwell** [comment]
Fet a local.
A les capses amb les opcions de resposta he ficat una alçada mínima de 84px i així quasi sempre son iguals. No puc posar una alçada fixa perque segons el contingut l'alçada ha de variar.

**Comment by andriusmp** [comment]
Ok!
