### ISSUE TITLE
Navegabilitat > fletxes

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#2]
A la pregunta 1, la fletxa esquerra salta a la penúltima pregunta (hauria d'anar a la última).
A l'última pregunta, la fletxa dreta salta a la segona pregunta (hauria d'anar a la primera).

**Comment by codwell** [comment]
A mi no em passa, no ho puc reproduir. 
De quin sector/subsector era el qüestionari?

**Comment by andriusmp** [comment]
Doncs a mí em passa amb tots els sectors que provo (Agroalimentari > Agricultura i ramaderia; Comercial > comerç a l'engròs i al detall d'altres productes, Industrial > Altres)

**Comment by codwell** [comment]
Corregit a local. Hi havia un bug que només era aparent en Chrome.

**Comment by andriusmp** [comment]
Ok!
