### ISSUE TITLE
Ordre dels sectors

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#20]
No me n'havia adonat que al desplegable del sector i dels subsectors, l'ordre no és el que sortia al Excel de continguts, si no que ho ordena alfabèticament. Queda una mica raro, perquè lo lògic és que 'altres' sempre estigui al final, i en molts casos surt com a primera opció.

**Comment by codwell** [comment]
Corregit a local. 
Pero ara tots estan ordenats per id, no se si es pitjor el problema que la solució...
La solució bona seria afegir un camp d'ordre a les dues taules, pero costa més de fer.

**Comment by andriusmp** [comment]
Perfecte! Jo crec que ja està bé així :)
