### ISSUE TITLE
Botó de càlcul

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#3]
El botó només s'activa quan, un cop respostes totes les preguntes, es fa clic a alguna de les fletxes. Això no és gaire intuïtiu. Podria activar-se just quan s'han respòs totes les preguntes, sense necessitat d'un últim clic?

**Comment by andriusmp** [comment]
Relacionat amb això, si un usuari té totes les preguntes respostes i el botó de càlcul activat, si desselecciona una pregunta, com que l'estat del botó no canvia de forma immediata, permet fer clic amb una resposta sense respondre. No passa a la pantalla d'informe, torna al qüestionari, però inclús arriba a mostrar el missatge 'Estàs segur...'. És un fluxe una mica raro.

**Comment by codwell** [comment]
Fet.

**Comment by andriusmp** [comment]
Ok!
