### ISSUE TITLE
Menú - Text i enllaços

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#5]
- El primer enllaç sempre ha de tenir el text 'Home', independentment de l'idioma.
- Els enllaços no s'estan obrint a pestanyes noves.
- Costa fer clic a 'Castellano', perquè l'àrea de selecció de la paraula 'Idioma' és molt gran.
- Molts enllaços, com comentaves, no funcionen. Jo he provat les URLs que vaig posar i funcionen.

**Comment by codwell** [comment]
Els primers 3 punts, corregits a local.

Respecte al quart: els enllaços que he ficat son els que em vas dir, ho pots comprovar passant el ratolí damunt.

Crec que el problema esta a la vostra web en el sentit de que crec que alguns enllaços només funcionen si son per a obrir una pàgina amb el mateix idioma que el actualment actiu a la vostra web.
La vostra web per defecte esta en castellà, si s'intenta entrar directament amb un enllaç que porta a una pàgina en anglès a voltes no funciona. 
He aconseguit que funcione (només a voltes) si primer entre en una altra pestanya a la vostra web, canvie l'idioma a anglés i després punxe en el enllaç de circular.

**Comment by codwell** [comment]
Avui, per exemple, estic a la vostra web en castellà, punxe en el vostre menu per anar a angles i torna a carregar la pàgina en castellà. Enllaç: http://www.ineditinnova.com/en
Es a dir, a voltes no hi ha manera de ficar-la en anglés. Això ja em va passar la setmana passada. La manera de gestionar els enllacos/idiomes a la vostra web es estranya i a voltes no funciona. No entenc el motiu.

**Comment by andriusmp** [comment]
Cert! Parlaré amb els de la web, perquè no sé què passa. Alguns matissos:
- En castellà em funciona perfect
- En anglès és quan passa això una mica raro
- En català, però, sí que estan posats malament els enllaços. Per exemple, no és http://ineditinnova.com/ca/equipo tal com està posat, si no http://www.ineditinnova.com/ca/equip

**Comment by codwell** [comment]
Tota la raó, no m'havia adonat d'aquests dos. El sistema que vàren utilitzar per a anomenar els enllaços va ser una mica lliure... ;)
Corregit a local.

**Comment by andriusmp** [comment]
Ok!
