### ISSUE TITLE
Pregunta 'Proximitat proveïdors'

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#7]
Alguna cosa ha passat amb el text de les respostes:
![image](https://user-images.githubusercontent.com/42779858/81545359-11f7cd80-9379-11ea-8f79-682a0bf92c88.png)

**Comment by andriusmp** [comment]
Crec que només passa en català

**Comment by codwell** [comment]
Si, hi va haver un error al fer la migració de dades. Corregit a local.

**Comment by andriusmp** [comment]
Ok!
