### ISSUE TITLE
+info

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#8]
Algunes coses que he trobat a la finestra de +info:

- P3: pot ser que siguin les imatges antigues? (potser només és en el cas de català?) Estan actualitzades a 'Continguts'.
- P3, P7,P14, P15, P16: poden justificar-se les llistes (guions / puntets / numeració) com està fet a la P9 i la P21 amb els punts?
- Posar en negreta tots els títols igual que s'ha fet a la P25.

**Comment by codwell** [comment]
No m'havia adonat que les imatges havien canviat. Corregit.
Millorada la presentació dels textos.

**Comment by andriusmp** [comment]
Ok!
