### ISSUE TITLE
Missatge de càlcul

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/nouencercla#9]
En aquesta finestra:
![image](https://user-images.githubusercontent.com/42779858/81551229-c695ed00-9381-11ea-93c1-9bf7d4a2b9b2.png)

Els botons no tenen el text correcte. Me n'adono que aquest text estava a les especificacions, però no als continguts. L'he afegit. Seria:
(ES): No, seguir revisando / Sí, calcular
(CA): No, seguir revisant / Sí, calcular
(EN): No, continue reviewing / Yes, calculate

**Comment by codwell** [comment]
Fet.

**Comment by andriusmp** [comment]
Ok!
